### ISSUE TITLE
Unable to find usable currency exchange rate from EUR to USD

### ISSUE THREAD

**Issue by meleyal** [wesabe/brcm-accounts-api#2]
No account data is loaded on the dashboard, I get 500 errors on the following ajax requests:

```
http://localhost:3000/data/accounts/all/EUR?_=1281811659442&include_archived=true
http://localhost:3000/data/analytics/summaries/monthly/20090815/20100815/EUR
```

Both respond with the message 'Unable to find usable currency exchange rate from EUR to USD'. Here's an example of the response:

```
 RuntimeError in BrcmController#passthrough

BRCM sucked at life: request to /data/accounts/all/EUR?_=1281811251655&include_archived=true received 500 response:

cache_controlmust-revalidate,no-cache,no-storecontent_typetext/html;charset=ISO-8859-1content_length5878

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Unable to find usable currency exchange rate from EUR to USD on 2010-08-14</title>
</head>
<body>
<h2>HTTP ERROR 500</h2>
<p>
  Problem accessing /v2/accounts/accounts/all/EUR. 
  Reason:
  Unable to find usable currency exchange rate from EUR to USD on 2010-08-14
</p>
<h3>Caused by:</h3>
com.wesabe.api.util.money.ExchangeRateNotFoundException: Unable to find usable currency exchange rate from EUR to USD on 2010-08-14
    at com.wesabe.api.util.money.CurrencyExchangeRateMap.getExchangeRate(CurrencyExchangeRateMap.java:171)
    at com.wesabe.api.util.money.DollarPivotCurrencyExchangeRateMap.getExchangeRate(DollarPivotCurrencyExchangeRateMap.java:33)
    at com.wesabe.api.util.money.Money.convert(Money.java:202)
    at com.wesabe.api.accounts.entities.AccountList.getTotal(AccountList.java:47)
    at com.wesabe.api.accounts.presenters.AccountGroupPresenter.present(AccountGroupPresenter.java:49)
    at com.wesabe.api.accounts.presenters.AccountListPresenter.present(AccountListPresenter.java:57)
    at com.wesabe.api.accounts.resources.OldAccountsResource.show(OldAccountsResource.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:156)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:208)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:75)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:115)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:67)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:724)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:689)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:680)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:324)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:425)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:604)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1211)
    at com.wideplay.warp.persist.SessionFilter$2.run(SessionFilter.java:68)
    at com.wideplay.warp.util.Lifecycles.failEarlyAndLeaveNoOneBehind(Lifecycles.java:29)
    at com.wideplay.warp.persist.SessionFilter.doFilter(SessionFilter.java:77)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1182)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:424)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:118)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:447)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:361)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:116)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:112)
    at org.eclipse.jetty.server.Server.handle(Server.java:337)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:546)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:973)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:530)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:203)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:399)
    at org.eclipse.jetty.server.bio.SocketConnector$Connection.run(SocketConnector.java:229)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:435)
    at java.lang.Thread.run(Thread.java:637)
```

**Comment by meleyal** [comment]
You need to manually add a currency / exchange rate to the database when you install PFC. I added the info to the install instructions http://github.com/wesabe/mesabe/wiki/Mesabe-DIY
